\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Clostridiumsensustricto1}};
    \node[mynode, below = 3.5 of m1] (m2){\textbf{Isobaculum}};
    \node[mynode, below = 3.5 of m2] (m3){\textbf{LachnospiraceaeUCG001}};
    \node[mynode, below = 3.5 of m3] (m4){\textbf{Victivallis}};
    \node[mynode, below = 3.5 of m4] (m5){\textbf{Colidextribacter}};
    
    % Treatments
    \node[mynode, left = 7 of m1](a) {\textbf{Fruit Portions} \\ Direct Effect: (-) $p = 0.138$ \\ Indirect Effect: (-) $p = 0.843$ \\ Total Effect: (-) $p = 0.263$};
    \node[mynode, below = 2 of a](b) {\textbf{vitamin A} \\ Direct Effect: (+) $p = 0.858$ \\ Indirect Effect: (+) $p = 0.912$ \\ Total Effect: (+) $p = 0.502$};
    \node[mynode, below = 2 of b](c) {\textbf{vitamin C} \\ Direct Effect: (-) $p = 0.466$ \\ Indirect Effect: (+) $p = 0.095^{.}$ \\ Total Effect: (+) $p = 0.353$};
    \node[mynode, below = 2 of c](d) {\textbf{Plant Protein} \\ Direct Effect: (+) $p = 0.300$ \\ Indirect Effect: (-) $p = 0.534$ \\ Total Effect: (+) $p = 0.384$};
    \node[mynode, below = 2 of d](e) {\textbf{Nutrient Score} \\ Direct Effect: (-) $p = 0.985$ \\ Indirect Effect: (+) $p = 0.769$ \\ Total Effect: (+) $p = 0.934$};
    \node[mynode, below = 2 of e](f) {\textbf{Fruit \& Vegetable Portions} \\ Direct Effect: (+) $p = 0.953$ \\ Indirect Effect: (+) $p = 0.903$ \\ Total Effect: (+) $p = 0.920$};
    
    
    % Health Outcomes
    \node[mynode, right = 5 of m3](g) {\textbf{Illness} \\ Comparative Fit $= 1.00$ \\ Tucker-Lewis $= 1.05$ \\ RMSEA $=0.00$ \\ SRMR $=0.092$};
    
    % Fruit Portions to mediators
    \draw[-latex] (a.east) -- node[pos=0.25, above, ,font=\footnotesize] {(-) $p = 0.832$} (m1.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.690^{.}$} (m2.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.528$} (m3.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.115$} (m4.west);
    
     % Vitamin A to mediators
    \draw[-latex] (b.east) -- node[auto,font=\footnotesize] {(-) $p = 0.192$} (m3.west);
    
     % Fruit Portions to mediators
    \draw[-latex] (c.east) -- node[auto,font=\footnotesize] {(-) $p = 0.284$} (m1.west);
    \draw[-latex] (c.east) -- node[auto,font=\footnotesize] {(+) $p = 0.025^{*}$} (m2.west);
    \draw[-latex] (c.east) -- node[auto,font=\footnotesize] {(+) $p = 0.758$} (m3.west);
    \draw[-latex] (c.east) -- node[auto,font=\footnotesize] {(-) $p = 0756$} (m4.west);
    \draw[-latex] (c.east) -- node[auto,font=\footnotesize] {(-) $p = 0.364$} (m5.west);
    
    % Plant Protein to mediators
    \draw[-latex] (d.east) -- node[auto,font=\footnotesize] {(+) $p = 0.532$} (m3.west);

    % Nutrient Score to mediators
    \draw[-latex] (e.east) -- node[auto,font=\footnotesize] {(-) $p = 0.766$} (m3.west);
    
    % Nutrient Score to mediators
    \draw[-latex] (f.east) -- node[auto,font=\footnotesize] {(-) $p = 0.904$} (m3.west);
    

    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {(-) $p = 0.005^{**}$} (g.north);
    \draw[-latex] (m2.east) -- node[auto,font=\footnotesize] {(+) $p = 0.029^{*}$} (g.west);
    \draw[-latex] (m3.east) -- node[auto,font=\footnotesize] {(-) $p = 0.003^{**}$} (g.west);
    \draw[-latex] (m4.east) -- node[auto,font=\footnotesize] {(-) $p < 0.001^{***}$} (g.west);
    \draw[-latex] (m5.east) -- node[auto,font=\footnotesize] {(-) $p = 0.009^{**}$} (g.south);
    
    

  \end{tikzpicture}
\end{document}