\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2.5 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Decanoylcarnitine}};
    \node[mynode, below = 0.5 of m1] (m2){\textbf{Phe.Val}};
    \node[mynode, below = 0.5 of m2] (m3){\textbf{Ala.Val}};
    \node[mynode, below = 0.5 of m3] (m4){\textbf{X15.Ketoprostaglandin.F2.alpha.}};
    \node[mynode, below = 0.5 of m4] (m5){\textbf{Thr.Leu}};
    
    % Treatments
    \node[mynode, left = 3 of m3](a) {\textbf{Vitamin A} \\ Direct Effect: (-) $p = 0.868$ \\ Indirect Effect: (+) $p = 0.098^{.}$ \\ Total Effect: (+) $p = 0.052^{.}$};
    
    % Health Outcomes
    \node[mynode, right = 3 of m3](b) {\textbf{Low Appetite} \\ Comparative Fit $= 0.158$ \\ Tucker-Lewis $= -0.264$ \\ RMSEA $=0.304$ \\ SRMR $=0.284$};
    
    % Vitamin A to mediators
    \draw[-latex] (a.north) -- node[auto,font=\footnotesize] {$(-)^{.}$} (m1.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {$(-)^{.}$} (m2.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {$(-)^{*}$} (m3.west);
    \draw[-latex] (a.east) -- node[below,font=\footnotesize] {$(-)$} (m4.west);
    \draw[-latex] (a.south) -- node[auto,font=\footnotesize] {$(-)^{*}$} (m5.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {$(-)^{.}$} (b.north);
    \draw[-latex] (m2.east) -- node[auto,font=\footnotesize] {$(-)$} (b.west);
    \draw[-latex] (m3.east) -- node[auto,font=\footnotesize] {$(-)^{.}$} (b.west);
    \draw[-latex] (m4.east) -- node[below,font=\footnotesize] {$(-)^{***}$} (b.west);
    \draw[-latex] (m5.east) -- node[auto,font=\footnotesize] {$(-)^{.}$} (b.south);
    

  \end{tikzpicture}
\end{document}