\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2.5 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Decanoylcarnitine}};
    \node[mynode, below = 1.5 of m1] (m2){\textbf{Phe.Val}};
    \node[mynode, below = 1.5 of m2] (m3){\textbf{Ala.Val}};
    \node[mynode, below = 1.5 of m3] (m4){\textbf{X15.Ketoprostaglandin.F2.alpha.}};
    \node[mynode, below = 1.5 of m4] (m5){\textbf{Thr.Leu}};
    
    % Treatments
    \node[mynode, left = 4 of m3](a) {\textbf{Vitamin A} \\ Direct Effect: (-) $p = 0.912$ \\ Indirect Effect: (+) $p = 0.072^{.}$ \\ Total Effect: (+) $p = 0.103$};
    
    % Health Outcomes
    \node[mynode, right = 4 of m3](b) {\textbf{Low Appetite} \\ Comparative Fit $= 0.153$ \\ Tucker-Lewis $= -0.271$ \\ RMSEA $=0.351$ \\ SRMR $=0.285$};
    
    % Vitamin A to mediators
    \draw[-latex] (a.north) -- node[auto,font=\footnotesize] {(-) $p = 0.064^{.}$} (m1.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.052^{.}$} (m2.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.048^{*}$} (m3.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(-) $p = 0.121$} (m4.west);
    \draw[-latex] (a.south) -- node[auto,font=\footnotesize] {(-) $p = 0.025^{*}$} (m5.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {(-) $p = 0.108$} (b.north);
    \draw[-latex] (m2.east) -- node[auto,font=\footnotesize] {(-) $p = 0.136$} (b.west);
    \draw[-latex] (m3.east) -- node[auto,font=\footnotesize] {(-) $p = 0.056^{.}$} (b.west);
    \draw[-latex] (m4.east) -- node[auto,font=\footnotesize] {(-) $p < 0.001^{***}$} (b.west);
    \draw[-latex] (m5.east) -- node[auto,font=\footnotesize] {(-) $p = 0.058^{.}$} (b.south);
    

  \end{tikzpicture}
\end{document}