\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Blautia}};
    \node[mynode, below = 0.75 of m1] (m2){\textbf{Catenisphaera}};
    \node[mynode, below = 0.75 of m2] (m3){\textbf{FamilyXIIIUCG001}};
    \node[mynode, below = 0.75 of m3] (m4){\textbf{Isobaculum}};
    
    % Treatments
    \node[mynode, left = 2 of m1](a) {\textbf{Grain Portions} \\ Direct Effect:(-)  $p = 0.129$ \\ Indirect Effect: (-) $p = 0.247$ \\ Total Effect: (-) $p = 0.038^{*}$};
    \node[mynode,below = 0.75 of a](b) {\textbf{Vitamin C} \\ Direct Effect: (-) $p = 0.928$ \\ Indirect Effect: (+) $p = 0.037^{*}$ \\ Total Effect: (+) $p = 0.080^{.}$};
    
    % Health Outcomes
    \node[mynode, right = 9.5 of b](d) {\textbf{Diarrhea} \\ Comparative Fit $= 0.493$ \\ Tucker-Lewis $= 0.493$ \\ RMSEA $=0.204$ \\ SRMR $=0.158$};
    
    % Grains to mediators
    \draw[-latex] (a.east) -- node[auto,font=\normalsize] {(-) .} (m1.west);
    
    % Vitamin C to mediators
    \draw[-latex] (b.east) -- node[auto,font=\normalsize] {(+)} (m2.west);
    \draw[-latex] (b.east) -- node[auto,font=\normalsize] {(-) .} (m3.west);
    \draw[-latex] (b.east) -- node[below,font=\normalsize] {(+)*} (m4.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\normalsize] {(+)} (d.north);
    \draw[-latex] (m2.east) -- node[auto,font=\normalsize] {(-)***} (d.west);
    \draw[-latex] (m3.east) -- node[below,font=\normalsize] {(+)***} (d.west);
    \draw[-latex] (m4.east) -- node[below,font=\normalsize] {(+)*} (d.west);
    
    

  \end{tikzpicture}
\end{document}