\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=3 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{X3.4.Dihydroxybenzoic.acid}};
    \node[mynode, below = 0.75 of m1] (m2){\textbf{Hamamelitannin}};
    \node[mynode, below = 0.75 of m2] (m3){\textbf{X6.Oxooctadecanoic.acid}};
    \node[mynode, below = 0.75 of m3] (m4){\textbf{Diisopropyl.phosphate}};
    
    % Treatments
    \node[mynode, left = 2 of m2](a) {\textbf{Grain Portions} \\ Direct Effect: (+) $p = 0.802$ \\ Indirect Effect: (-) $p = 0.051^{.}$ \\ Total Effect: (-) $p = 0.041^{*}$};
    \node[mynode,below = 0.5 of a](b) {\textbf{Vitamin C} \\ Direct Effect: (-) $p = 0.958$ \\ Indirect Effect: (+) $p = 0.096^{.}$ \\ Total Effect: (+) $p = 0.136$};
    
    % Health Outcomes
    \node[mynode, right = 2 of m3](d) {\textbf{Diarrhea} \\ Comparative Fit $= 0.920$ \\ Tucker-Lewis $= 0.920$ \\ RMSEA $=0.153$ \\ SRMR $=0.226$};
    
    % Grains to mediators
    \draw[-latex] (a.east) -- node[auto,font=\normalsize] {(-)**} (m1.west);
    \draw[-latex] (a.east) -- node[auto,font=\normalsize] {(-)**} (m2.west);
    \draw[-latex] (a.east) -- node[auto,font=\normalsize] {(-)*} (m3.west);   
    
    % Vitamin C to mediators
    \draw[-latex] (b.east) -- node[auto,font=\normalsize] {(+) .} (m4.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\normalsize] {(+)*} (d.north);
    \draw[-latex] (m2.east) -- node[auto,font=\normalsize] {(+)*} (d.west);
    \draw[-latex] (m3.east) -- node[auto,font=\normalsize] {(+).} (d.west);
    \draw[-latex] (m4.east) -- node[below,font=\normalsize] {(+)***} (d.west);
    
    

  \end{tikzpicture}
\end{document}