\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Aniline}};
    
    % Treatments
    \node[mynode, left = 1 of m1](a) {\textbf{Fruit \& Vegetable Portions} \\ Direct Effect: (+) $p = 0.118$ \\ Indirect Effect: (+) $p = 0.200$ \\ Total Effect: (+) $p = 0.038^{*}$};
    
    % Health Outcomes
    \node[mynode, right = 1 of m1](b) {\textbf{Abdominal Pain} \\ Comparative Fit $= 1$ \\ Tucker-Lewis $= 1$ \\ RMSEA $=$ NA \\ SRMR $=$ NA};
    
    % Fruit to mediators
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {$(+)$} (m1.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {$(+)^{*}$} (b.west);
    
    

  \end{tikzpicture}
\end{document}