\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Aniline}};
    
    % Treatments
    \node[mynode, left = 3 of m1](a) {\textbf{Fruit \& Vegetable Portions} \\ Direct Effect: (+) $p = 0.110$ \\ (+) Indirect Effect: $p = 0.135$ \\ Total Effect: (+) $p = 0.019^{*}$};
    
    % Health Outcomes
    \node[mynode, right = 3 of m1](b) {\textbf{Abdominal Pain} \\ Comparative Fit $= 1$ \\ Tucker-Lewis $= 1$ \\ RMSEA $=0$ \\ SRMR $=0$};
    
    % Fruit to mediators
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(+) $p = 0.025^{*}$} (m1.west);
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {(+) $p = 0.042^{*}$} (b.west);
    
    

  \end{tikzpicture}
\end{document}