\documentclass[tikz,border=4]{standalone}\usepackage{siunitx}
\usetikzlibrary{positioning}
\tikzset{mynode/.style={draw,text width=2 in,align=center}
}
\begin{document}
  \begin{tikzpicture}
  
  % Mediators
    \node[mynode] (m1){\textbf{Hespellia}};
    \node[mynode, below = 1.5 of m1] (m2){\textbf{Mobiluncus}};
    \node[mynode, below = 1.5 of m2] (m3){\textbf{Papillibacter}};
    
    % Treatments
    \node[mynode, left = 3 of m2](a) {\textbf{Fruit \& Vegetable Portions} \\ Direct Effect: $p = 0.786$ \\ Indirect Effect: $p = 0.044^{*}$ \\ Total Effect: $p = 0.014^{*}$};
    
    % Health Outcomes
    \node[mynode, right = 3 of m2](b) {\textbf{Abdominal Pain} \\ Comparative Fit $= 0.985$ \\ Tucker-Lewis $= 0.970$ \\ RMSEA $=0.029$ \\ SRMR $=0.067$};
    
    % Fruit to mediators
    \draw[-latex] (a.north) -- node[auto,font=\footnotesize] {(+) $p = 0.032^{*}$} (m1.west);
    \draw[-latex] (a.east) -- node[auto,font=\footnotesize] {(+) $p = 0.024^{.}$} (m2.west);
    \draw[-latex] (a.south) -- node[auto,font=\footnotesize] {(-) $p = 0.121$} (m3.west);
    
    
    % Mediators to outcome
    \draw[-latex] (m1.east) -- node[auto,font=\footnotesize] {(+) $p < 0.001^{***}$} (b.north);
    \draw[-latex] (m2.east) -- node[auto,font=\footnotesize] {(-) $p = 0.077^{.}$} (b.west);
    \draw[-latex] (m3.east) -- node[auto,font=\footnotesize] {(+) $p 0.025^{*}$} (b.south);
    
    

  \end{tikzpicture}
\end{document}